import { LayoutTemplate } from '../types'

export const templates6to10: LayoutTemplate[] = [
  {
    id: 'hexa-grid-3x2',
    photoCount: 6,
    gridTemplate: 'repeat(3, 1fr) / repeat(2, 1fr)',
    gridAreas: '"a b" "c d" "e f"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f'],
  },
  {
    id: 'hexa-grid-2x3',
    photoCount: 6,
    gridTemplate: 'repeat(2, 1fr) / repeat(3, 1fr)',
    gridAreas: '"a b c" "d e f"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f'],
  },
  {
    id: 'hexa-top-hero',
    photoCount: 6,
    gridTemplate: 'repeat(3, 1fr) / repeat(6, 1fr)',
    gridAreas: '"a a a a a a" "b b b c c c" "d d e e f f"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f'],
  },
  {
    id: 'hexa-bottom-hero',
    photoCount: 6,
    gridTemplate: 'repeat(3, 1fr) / repeat(6, 1fr)',
    gridAreas: '"a a b b c c" "d d d e e e" "f f f f f f"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f'],
  },
  {
    id: 'hexa-mixed-rows',
    photoCount: 6,
    gridTemplate: 'repeat(3, 1fr) / repeat(3, 1fr)',
    gridAreas: '"a a b" "c d d" "e e f"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f'],
  },
  {
    id: 'hexa-left-hero',
    photoCount: 6,
    gridTemplate: 'repeat(3, 1fr) / repeat(3, 1fr)',
    gridAreas: '"a a b" "a a c" "d e f"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f'],
  },
  {
    id: 'hexa-right-hero',
    photoCount: 6,
    gridTemplate: 'repeat(3, 1fr) / repeat(3, 1fr)',
    gridAreas: '"a b b" "c b b" "d e f"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f'],
  },
  {
    id: 'hexa-top-wide',
    photoCount: 6,
    gridTemplate: 'repeat(3, 1fr) / repeat(5, 1fr)',
    gridAreas: '"a a a a a" "a a a a a" "b c d e f"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f'],
  },
  {
    id: 'hexa-balanced',
    photoCount: 6,
    gridTemplate: 'repeat(4, 1fr) / repeat(4, 1fr)',
    gridAreas: '"a a b c" "a a b c" "d e f f" "d e f f"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f'],
  },
  {
    id: 'septa-dual-hero',
    photoCount: 7,
    gridTemplate: 'repeat(4, 1fr) / repeat(4, 1fr)',
    gridAreas: '"a a b b" "a a b b" "c c d e" "c c f g"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g'],
  },
  {
    id: 'septa-h-band',
    photoCount: 7,
    gridTemplate: 'repeat(3, 1fr) / repeat(3, 1fr)',
    gridAreas: '"a b c" "d d d" "e f g"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g'],
  },
  {
    id: 'septa-v-band',
    photoCount: 7,
    gridTemplate: 'repeat(3, 1fr) / repeat(3, 1fr)',
    gridAreas: '"a b c" "d b e" "f b g"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g'],
  },
  {
    id: 'septa-left-tall',
    photoCount: 7,
    gridTemplate: 'repeat(4, 1fr) / repeat(2, 1fr)',
    gridAreas: '"a b" "a c" "d e" "f g"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g'],
  },
  {
    id: 'septa-top-wide',
    photoCount: 7,
    gridTemplate: 'repeat(3, 1fr) / repeat(3, 1fr)',
    gridAreas: '"a a a" "b c d" "e f g"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g'],
  },
  {
    id: 'septa-bottom-wide',
    photoCount: 7,
    gridTemplate: 'repeat(3, 1fr) / repeat(3, 1fr)',
    gridAreas: '"a b c" "d e f" "g g g"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g'],
  },
  {
    id: 'septa-mixed-split',
    photoCount: 7,
    gridTemplate: 'repeat(3, 1fr) / repeat(6, 1fr)',
    gridAreas: '"a a a b b b" "c c d d e e" "f f f g g g"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g'],
  },
  {
    id: 'septa-asymmetric',
    photoCount: 7,
    gridTemplate: 'repeat(3, 1fr) / repeat(3, 1fr)',
    gridAreas: '"a b b" "c d e" "f g g"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g'],
  },
  {
    id: 'octa-grid-4x2',
    photoCount: 8,
    gridTemplate: 'repeat(4, 1fr) / repeat(2, 1fr)',
    gridAreas: '"a b" "c d" "e f" "g h"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'],
  },
  {
    id: 'octa-grid-2x4',
    photoCount: 8,
    gridTemplate: 'repeat(2, 1fr) / repeat(4, 1fr)',
    gridAreas: '"a b c d" "e f g h"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'],
  },
  {
    id: 'octa-mixed-blocks',
    photoCount: 8,
    gridTemplate: 'repeat(4, 1fr) / repeat(4, 1fr)',
    gridAreas: '"a a b c" "d d b c" "e f g g" "e f h h"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'],
  },
  {
    id: 'octa-sandwich',
    photoCount: 8,
    gridTemplate: 'repeat(4, 1fr) / repeat(3, 1fr)',
    gridAreas: '"h h h" "a b c" "d e f" "g g g"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'],
  },
  {
    id: 'octa-dual-hero',
    photoCount: 8,
    gridTemplate: 'repeat(5, 1fr) / repeat(4, 1fr)',
    gridAreas: '"a a b b" "a a b b" "c d e f" "g g h h" "g g h h"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'],
  },
  {
    id: 'nona-grid-3x3',
    photoCount: 9,
    gridTemplate: 'repeat(3, 1fr) / repeat(3, 1fr)',
    gridAreas: '"a b c" "d e f" "g h i"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'],
  },
  {
    id: 'nona-top-hero',
    photoCount: 9,
    gridTemplate: 'repeat(3, 1fr) / repeat(4, 1fr)',
    gridAreas: '"a a a a" "b c d e" "f g h i"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'],
  },
  {
    id: 'nona-center-hero',
    photoCount: 9,
    gridTemplate: 'repeat(3, 1fr) / repeat(4, 1fr)',
    gridAreas: '"a b c d" "e e e e" "f g h i"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'],
  },
  {
    id: 'nona-bottom-hero',
    photoCount: 9,
    gridTemplate: 'repeat(3, 1fr) / repeat(4, 1fr)',
    gridAreas: '"a b c d" "e f g h" "i i i i"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'],
  },
  {
    id: 'nona-left-hero',
    photoCount: 9,
    gridTemplate: 'repeat(3, 1fr) / repeat(4, 1fr)',
    gridAreas: '"a a b c" "a a d e" "f g h i"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'],
  },
  {
    id: 'nona-right-hero',
    photoCount: 9,
    gridTemplate: 'repeat(3, 1fr) / repeat(4, 1fr)',
    gridAreas: '"a b c d" "e f g g" "h i g g"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'],
  },
  {
    id: 'nona-center-block',
    photoCount: 9,
    gridTemplate: 'repeat(4, 1fr) / repeat(4, 1fr)',
    gridAreas: '"a a b b" "c d d e" "c d d e" "f g h i"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'],
  },
  {
    id: 'deca-grid-5x2',
    photoCount: 10,
    gridTemplate: 'repeat(5, 1fr) / repeat(2, 1fr)',
    gridAreas: '"a b" "c d" "e f" "g h" "i j"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'],
  },
  {
    id: 'deca-top-dual',
    photoCount: 10,
    gridTemplate: 'repeat(3, 1fr) / repeat(4, 1fr)',
    gridAreas: '"a a b b" "c d e f" "g h i j"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'],
  },
  {
    id: 'deca-center-dual',
    photoCount: 10,
    gridTemplate: 'repeat(3, 1fr) / repeat(4, 1fr)',
    gridAreas: '"a b c d" "e e f f" "g h i j"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'],
  },
  {
    id: 'deca-top-hero',
    photoCount: 10,
    gridTemplate: 'repeat(4, 1fr) / repeat(3, 1fr)',
    gridAreas: '"a a a" "b c d" "e f g" "h i j"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'],
  },
  {
    id: 'deca-left-hero',
    photoCount: 10,
    gridTemplate: 'repeat(4, 1fr) / repeat(4, 1fr)',
    gridAreas: '"a a b c" "a a d e" "f g h h" "i j h h"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'],
  },
  {
    id: 'deca-balanced',
    photoCount: 10,
    gridTemplate: 'repeat(6, 1fr) / repeat(6, 1fr)',
    gridAreas:
      '"a a b b c c" "a a b b c c" "d d e e f f" "d d g g f f" "h h i i j j" "h h i i j j"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'],
  },
]
