import { LayoutTemplate } from '../store'

export const templates1to5: LayoutTemplate[] = [
  {
    id: 'dual-horizontal',
    photoCount: 2,
    gridTemplate: 'repeat(1, 1fr) / repeat(2, 1fr)',
    gridAreas: '"a b"',
    areas: ['a', 'b'],
  },
  {
    id: 'dual-vertical',
    photoCount: 2,
    gridTemplate: 'repeat(2, 1fr) / repeat(1, 1fr)',
    gridAreas: '"a" "b"',
    areas: ['a', 'b'],
  },
  {
    id: 'tri-top-wide',
    photoCount: 3,
    gridTemplate: 'repeat(2, 1fr) / repeat(2, 1fr)',
    gridAreas: '"a a" "b c"',
    areas: ['a', 'b', 'c'],
  },
  {
    id: 'tri-left-tall',
    photoCount: 3,
    gridTemplate: 'repeat(2, 1fr) / repeat(2, 1fr)',
    gridAreas: '"a b" "a c"',
    areas: ['a', 'b', 'c'],
  },
  {
    id: 'tri-right-tall',
    photoCount: 3,
    gridTemplate: 'repeat(2, 1fr) / repeat(2, 1fr)',
    gridAreas: '"a b" "c b"',
    areas: ['a', 'b', 'c'],
  },
  {
    id: 'tri-bottom-wide',
    photoCount: 3,
    gridTemplate: 'repeat(2, 1fr) / repeat(2, 1fr)',
    gridAreas: '"a b" "c c"',
    areas: ['a', 'b', 'c'],
  },
  {
    id: 'tri-columns',
    photoCount: 3,
    gridTemplate: 'repeat(3, 1fr) / repeat(3, 1fr)',
    gridAreas: '"a b c" "a b c" "a b c"',
    areas: ['a', 'b', 'c'],
  },
  {
    id: 'tri-left-hero',
    photoCount: 3,
    gridTemplate: 'repeat(3, 1fr) / repeat(3, 1fr)',
    gridAreas: '"a a b" "a a c" "a a c"',
    areas: ['a', 'b', 'c'],
  },
  {
    id: 'quad-grid',
    photoCount: 4,
    gridTemplate: 'repeat(2, 1fr) / repeat(2, 1fr)',
    gridAreas: '"a b" "c d"',
    areas: ['a', 'b', 'c', 'd'],
  },
  {
    id: 'quad-top-hero',
    photoCount: 4,
    gridTemplate: 'repeat(2, 1fr) / repeat(3, 1fr)',
    gridAreas: '"a a a" "b c d"',
    areas: ['a', 'b', 'c', 'd'],
  },
  {
    id: 'quad-bottom-hero',
    photoCount: 4,
    gridTemplate: 'repeat(2, 1fr) / repeat(3, 1fr)',
    gridAreas: '"a b c" "d d d"',
    areas: ['a', 'b', 'c', 'd'],
  },
  {
    id: 'quad-left-hero',
    photoCount: 4,
    gridTemplate: 'repeat(3, 1fr) / repeat(2, 1fr)',
    gridAreas: '"a b" "a c" "a d"',
    areas: ['a', 'b', 'c', 'd'],
  },
  {
    id: 'quad-columns',
    photoCount: 4,
    gridTemplate: 'repeat(4, 1fr) / repeat(4, 1fr)',
    gridAreas: '"a b c d" "a b c d" "a b c d" "a b c d"',
    areas: ['a', 'b', 'c', 'd'],
  },
  {
    id: 'quad-left-split',
    photoCount: 4,
    gridTemplate: 'repeat(2, 1fr) / repeat(3, 1fr)',
    gridAreas: '"a b b" "a c d"',
    areas: ['a', 'b', 'c', 'd'],
  },
  {
    id: 'quad-right-split',
    photoCount: 4,
    gridTemplate: 'repeat(2, 1fr) / repeat(3, 1fr)',
    gridAreas: '"b b c" "a d c"',
    areas: ['a', 'b', 'c', 'd'],
  },
  {
    id: 'quad-sandwich',
    photoCount: 4,
    gridTemplate: 'repeat(3, 1fr) / repeat(2, 1fr)',
    gridAreas: '"a a" "b c" "d d"',
    areas: ['a', 'b', 'c', 'd'],
  },
  {
    id: 'penta-top-hero',
    photoCount: 5,
    gridTemplate: 'repeat(2, 1fr) / repeat(3, 1fr)',
    gridAreas: '"a a b" "c d e"',
    areas: ['a', 'b', 'c', 'd', 'e'],
  },
  {
    id: 'penta-left-tall',
    photoCount: 5,
    gridTemplate: 'repeat(3, 1fr) / repeat(2, 1fr)',
    gridAreas: '"a b" "a c" "d e"',
    areas: ['a', 'b', 'c', 'd', 'e'],
  },
  {
    id: 'penta-center-mix',
    photoCount: 5,
    gridTemplate: 'repeat(3, 1fr) / repeat(3, 1fr)',
    gridAreas: '"a a b" "c d b" "c e e"',
    areas: ['a', 'b', 'c', 'd', 'e'],
  },
  {
    id: 'penta-right-hero',
    photoCount: 5,
    gridTemplate: 'repeat(3, 1fr) / repeat(3, 1fr)',
    gridAreas: '"a b b" "c d d" "e d d"',
    areas: ['a', 'b', 'c', 'd', 'e'],
  },
  {
    id: 'penta-columns',
    photoCount: 5,
    gridTemplate: 'repeat(3, 1fr) / repeat(3, 1fr)',
    gridAreas: '"a b c" "a d c" "a e c"',
    areas: ['a', 'b', 'c', 'd', 'e'],
  },
  {
    id: 'penta-center-bar',
    photoCount: 5,
    gridTemplate: 'repeat(3, 1fr) / repeat(2, 1fr)',
    gridAreas: '"e a" "b b" "c d"',
    areas: ['a', 'b', 'c', 'd', 'e'],
  },
  {
    id: 'penta-split-even',
    photoCount: 5,
    gridTemplate: 'repeat(2, 1fr) / repeat(6, 1fr)',
    gridAreas: '"a a a b b b" "c c d d e e"',
    areas: ['a', 'b', 'c', 'd', 'e'],
  },
  {
    id: 'penta-left-stack',
    photoCount: 5,
    gridTemplate: 'repeat(4, 1fr) / repeat(2, 1fr)',
    gridAreas: '"a b" "a c" "a d" "a e"',
    areas: ['a', 'b', 'c', 'd', 'e'],
  },
  {
    id: 'penta-bottom-grid',
    photoCount: 5,
    gridTemplate: 'repeat(3, 1fr) / repeat(2, 1fr)',
    gridAreas: '"e e" "a b" "c d"',
    areas: ['a', 'b', 'c', 'd', 'e'],
  },
  {
    id: 'penta-asymmetric',
    photoCount: 5,
    gridTemplate: 'repeat(3, 1fr) / repeat(3, 1fr)',
    gridAreas: '"d e e" "d a b" "d c c"',
    areas: ['a', 'b', 'c', 'd', 'e'],
  },
]
