import { LayoutTemplate } from '../store'

export const templates11to16: LayoutTemplate[] = [
  {
    id: 'eleven-center-hero',
    photoCount: 11,
    gridTemplate: 'repeat(4, 1fr) / repeat(4, 1fr)',
    gridAreas: '"a b c d" "e f f g" "e f f g" "h i j k"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k'],
  },
  {
    id: 'eleven-mixed-blocks',
    photoCount: 11,
    gridTemplate: 'repeat(4, 1fr) / repeat(4, 1fr)',
    gridAreas: '"a b b c" "d e e f" "g e e h" "i j j k"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k'],
  },
  {
    id: 'eleven-rows-split',
    photoCount: 11,
    gridTemplate: 'repeat(4, 1fr) / repeat(6, 1fr)',
    gridAreas: '"a a a b b b" "c c d d e e" "f f g g h h" "i i j j k k"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k'],
  },
  {
    id: 'eleven-top-hero',
    photoCount: 11,
    gridTemplate: 'repeat(3, 1fr) / repeat(5, 1fr)',
    gridAreas: '"a a a a a" "b c d e f" "g h i j k"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k'],
  },
  {
    id: 'eleven-center-band',
    photoCount: 11,
    gridTemplate: 'repeat(3, 1fr) / repeat(5, 1fr)',
    gridAreas: '"a b c d e" "f f f f f" "g h i j k"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k'],
  },
  {
    id: 'eleven-left-tall',
    photoCount: 11,
    gridTemplate: 'repeat(5, 1fr) / repeat(3, 1fr)',
    gridAreas: '"a a b" "a a c" "d e f" "g h i" "j k k"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k'],
  },
  {
    id: 'twelve-grid-4x3',
    photoCount: 12,
    gridTemplate: 'repeat(4, 1fr) / repeat(3, 1fr)',
    gridAreas: '"a b c" "d e f" "g h i" "j k l"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l'],
  },
  {
    id: 'twelve-grid-3x4',
    photoCount: 12,
    gridTemplate: 'repeat(3, 1fr) / repeat(4, 1fr)',
    gridAreas: '"a b c d" "e f g h" "i j k l"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l'],
  },
  {
    id: 'twelve-center-hero',
    photoCount: 12,
    gridTemplate: 'repeat(4, 1fr) / repeat(4, 1fr)',
    gridAreas: '"a b c d" "e f f g" "h f f i" "j k l l"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l'],
  },
  {
    id: 'twelve-grid-6x2',
    photoCount: 12,
    gridTemplate: 'repeat(6, 1fr) / repeat(2, 1fr)',
    gridAreas: '"a b" "c d" "e f" "g h" "i j" "k l"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l'],
  },
  {
    id: 'twelve-mixed-rows',
    photoCount: 12,
    gridTemplate: 'repeat(4, 1fr) / repeat(6, 1fr)',
    gridAreas: '"a a b b c c" "d d d e e e" "f f g g h h" "i i j j k l"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l'],
  },
  {
    id: 'twelve-top-left-hero',
    photoCount: 12,
    gridTemplate: 'repeat(4, 1fr) / repeat(4, 1fr)',
    gridAreas: '"a a b c" "a a d e" "f g h i" "j k l l"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l'],
  },
  {
    id: 'thirteen-center-hero',
    photoCount: 13,
    gridTemplate: 'repeat(4, 1fr) / repeat(4, 1fr)',
    gridAreas: '"a b c d" "e f f g" "h f f i" "j k l m"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm'],
  },
  {
    id: 'thirteen-top-left-hero',
    photoCount: 13,
    gridTemplate: 'repeat(4, 1fr) / repeat(4, 1fr)',
    gridAreas: '"a a b c" "a a d e" "f g h i" "j k l m"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm'],
  },
  {
    id: 'thirteen-bottom-right-hero',
    photoCount: 13,
    gridTemplate: 'repeat(4, 1fr) / repeat(4, 1fr)',
    gridAreas: '"a b c d" "e f g h" "i j k k" "l m k k"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm'],
  },
  {
    id: 'thirteen-grid-5x3',
    photoCount: 13,
    gridTemplate: 'repeat(5, 1fr) / repeat(3, 1fr)',
    gridAreas: '"a a b" "c d e" "f g h" "i j k" "l m m"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm'],
  },
  {
    id: 'thirteen-top-dual',
    photoCount: 13,
    gridTemplate: 'repeat(4, 1fr) / repeat(4, 1fr)',
    gridAreas: '"a a b b" "c d e f" "g h i j" "k l m m"',
    areas: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm'],
  },
  {
    id: 'fourteen-grid-7x2',
    photoCount: 14,
    gridTemplate: 'repeat(7, 1fr) / repeat(2, 1fr)',
    gridAreas: '"a b" "c d" "e f" "g h" "i j" "k l" "m n"',
    areas: [
      'a',
      'b',
      'c',
      'd',
      'e',
      'f',
      'g',
      'h',
      'i',
      'j',
      'k',
      'l',
      'm',
      'n',
    ],
  },
  {
    id: 'fourteen-mixed-blocks',
    photoCount: 14,
    gridTemplate: 'repeat(4, 1fr) / repeat(4, 1fr)',
    gridAreas: '"a b c d" "e f f g" "h i i j" "k l m n"',
    areas: [
      'a',
      'b',
      'c',
      'd',
      'e',
      'f',
      'g',
      'h',
      'i',
      'j',
      'k',
      'l',
      'm',
      'n',
    ],
  },
  {
    id: 'fourteen-center-dual',
    photoCount: 14,
    gridTemplate: 'repeat(4, 1fr) / repeat(4, 1fr)',
    gridAreas: '"a b c d" "e f g h" "i f g j" "k l m n"',
    areas: [
      'a',
      'b',
      'c',
      'd',
      'e',
      'f',
      'g',
      'h',
      'i',
      'j',
      'k',
      'l',
      'm',
      'n',
    ],
  },
  {
    id: 'fourteen-grid-5x3',
    photoCount: 14,
    gridTemplate: 'repeat(5, 1fr) / repeat(3, 1fr)',
    gridAreas: '"a a b" "c d e" "f g h" "i j k" "l m n"',
    areas: [
      'a',
      'b',
      'c',
      'd',
      'e',
      'f',
      'g',
      'h',
      'i',
      'j',
      'k',
      'l',
      'm',
      'n',
    ],
  },
  {
    id: 'fifteen-grid-5x3',
    photoCount: 15,
    gridTemplate: 'repeat(5, 1fr) / repeat(3, 1fr)',
    gridAreas: '"a b c" "d e f" "g h i" "j k l" "m n o"',
    areas: [
      'a',
      'b',
      'c',
      'd',
      'e',
      'f',
      'g',
      'h',
      'i',
      'j',
      'k',
      'l',
      'm',
      'n',
      'o',
    ],
  },
  {
    id: 'fifteen-center-hero',
    photoCount: 15,
    gridTemplate: 'repeat(4, 1fr) / repeat(4, 1fr)',
    gridAreas: '"a b c d" "e f f g" "h i j k" "l m n o"',
    areas: [
      'a',
      'b',
      'c',
      'd',
      'e',
      'f',
      'g',
      'h',
      'i',
      'j',
      'k',
      'l',
      'm',
      'n',
      'o',
    ],
  },
  {
    id: 'fifteen-bottom-wide',
    photoCount: 15,
    gridTemplate: 'repeat(4, 1fr) / repeat(4, 1fr)',
    gridAreas: '"a b c d" "e f g h" "i j k l" "m n o o"',
    areas: [
      'a',
      'b',
      'c',
      'd',
      'e',
      'f',
      'g',
      'h',
      'i',
      'j',
      'k',
      'l',
      'm',
      'n',
      'o',
    ],
  },
  {
    id: 'fifteen-grid-3x5',
    photoCount: 15,
    gridTemplate: 'repeat(3, 1fr) / repeat(5, 1fr)',
    gridAreas: '"a b c d e" "f g h i j" "k l m n o"',
    areas: [
      'a',
      'b',
      'c',
      'd',
      'e',
      'f',
      'g',
      'h',
      'i',
      'j',
      'k',
      'l',
      'm',
      'n',
      'o',
    ],
  },
  {
    id: 'sixteen-grid-4x4',
    photoCount: 16,
    gridTemplate: 'repeat(4, 1fr) / repeat(4, 1fr)',
    gridAreas: '"a b c d" "e f g h" "i j k l" "m n o p"',
    areas: [
      'a',
      'b',
      'c',
      'd',
      'e',
      'f',
      'g',
      'h',
      'i',
      'j',
      'k',
      'l',
      'm',
      'n',
      'o',
      'p',
    ],
  },
  {
    id: 'sixteen-grid-8x2',
    photoCount: 16,
    gridTemplate: 'repeat(8, 1fr) / repeat(2, 1fr)',
    gridAreas: '"a b" "c d" "e f" "g h" "i j" "k l" "m n" "o p"',
    areas: [
      'a',
      'b',
      'c',
      'd',
      'e',
      'f',
      'g',
      'h',
      'i',
      'j',
      'k',
      'l',
      'm',
      'n',
      'o',
      'p',
    ],
  },
  {
    id: 'sixteen-grid-2x8',
    photoCount: 16,
    gridTemplate: 'repeat(2, 1fr) / repeat(8, 1fr)',
    gridAreas: '"a b c d e f g h" "i j k l m n o p"',
    areas: [
      'a',
      'b',
      'c',
      'd',
      'e',
      'f',
      'g',
      'h',
      'i',
      'j',
      'k',
      'l',
      'm',
      'n',
      'o',
      'p',
    ],
  },
]
